const db = require('../config/db');
const appUserRepository = require('../repositories/appUser.repository');
const eventRepository = require('../repositories/event.repository');
const rawLiveEventRepository = require('../repositories/rawLiveEvent.repository');
const { makeLogger } = require('../utils/logger');

const logger = makeLogger('eventBatch');

const MAX_BATCH_SIZE = 100;
const FLUSH_INTERVAL_MS = 2000;

/** Queued items awaiting the next flush -- see enqueue() for the shape. */
let queue = [];
let flushTimer = null;
let inFlight = null;

/**
 * AsyncEventBatcher: buffers a CHAT/GIFT/JOIN event for Postgres persistence
 * instead of writing it immediately. `enqueue()` itself is a synchronous
 * array push -- no DB call happens on this call, so it adds ~0 overhead to
 * the Fast-Path Socket broadcast it's called right after in
 * liveStream.service.js (which was already fire-and-forget before this, but
 * still did a DB round trip per event).
 *
 * @param {{sessionId: number, eventType: 'CHAT'|'GIFT'|'JOIN', user: object,
 *   occurredAt: Date|undefined, extra: object, envelope: object}} item
 */
function enqueue(item) {
  queue.push(item);
  if (queue.length >= MAX_BATCH_SIZE) {
    flushInBackground();
  }
}

/** Starts the periodic flush timer. Call once at server startup. */
function init() {
  if (!flushTimer) {
    flushTimer = setInterval(flushInBackground, FLUSH_INTERVAL_MS);
  }
}

/** Background callers consume rejection; the retained batch retries on the next tick. */
function flushInBackground() {
  flush().catch((err) => {
    logger.error('Batch flush deferred; events retained for retry', { error: err.message });
  });
}

/** Serialize writes and wait for existing writes before draining newer events. */
function flush() {
  if (inFlight) return inFlight;
  if (queue.length === 0) return Promise.resolve();
  inFlight = drain().finally(() => { inFlight = null; });
  return inFlight;
}

async function drain() {
  while (queue.length > 0) {
    const batch = queue.splice(0, MAX_BATCH_SIZE);
    await writeBatch(batch);
  }
}

async function writeBatch(batch) {
  let client;
  try {
    client = await db.pool.connect();
    await client.query('BEGIN');

    // app_users: de-dupe by tiktokUserId first -- a single INSERT ... ON
    // CONFLICT DO UPDATE statement can't touch the same conflicting row
    // twice. Last occurrence in the batch wins, matching the old per-event
    // upsert()'s "refreshed on every appearance" behavior.
    const usersByTiktokId = new Map();
    for (const item of batch) {
      usersByTiktokId.set(item.user.userId, {
        tiktokUserId: item.user.userId,
        username: item.user.uniqueId,
        nickname: item.user.nickname,
      });
    }
    const appUserIdByTiktokId = await appUserRepository.bulkUpsert(client, [...usersByTiktokId.values()]);

    // events + payloads: grouped by type, because comment/gift/join_payloads
    // each need the events.id FK generated by inserting into `events` first.
    for (const eventType of ['CHAT', 'GIFT', 'JOIN']) {
      const items = batch.filter((item) => item.eventType === eventType);
      if (items.length === 0) {
        continue;
      }

      const eventIds = await eventRepository.bulkInsertEvents(
        client,
        items.map((item) => ({
          sessionId: item.sessionId,
          appUserId: appUserIdByTiktokId.get(item.user.userId),
          eventType,
          occurredAt: item.occurredAt,
        }))
      );

      if (eventType === 'CHAT') {
        await eventRepository.bulkInsertCommentPayloads(
          client,
          items.map((item, idx) => ({ eventId: eventIds[idx], comment: item.extra.comment }))
        );
      } else if (eventType === 'GIFT') {
        await eventRepository.bulkInsertGiftPayloads(
          client,
          items.map((item, idx) => ({ eventId: eventIds[idx], ...item.extra }))
        );
      } else {
        await eventRepository.bulkInsertJoinPayloads(
          client,
          items.map((item, idx) => ({ eventId: eventIds[idx], viewerCount: item.extra.viewerCount }))
        );
      }
    }

    // Keep raw and normalized writes in the same transaction.
    await rawLiveEventRepository.bulkCreate(
      client,
      batch.map((item) => ({
        eventId: item.envelope.eventId,
        sessionId: item.sessionId,
        eventType: item.envelope.type,
        rawPayload: item.envelope,
      }))
    );

    await client.query('COMMIT');
    logger.debug(`Flushed batch of ${batch.length} event(s)`);
  } catch (err) {
    if (client) await client.query('ROLLBACK').catch(() => {});
    queue = batch.concat(queue);
    throw err;
  } finally {
    if (client) client.release();
  }
}

module.exports = { init, enqueue, flush };
