const db = require('../config/db');
const appUserRepository = require('../repositories/appUser.repository');
const eventRepository = require('../repositories/event.repository');
const rawLiveEventRepository = require('../repositories/rawLiveEvent.repository');
const { makeLogger } = require('../utils/logger');

const logger = makeLogger('eventBatch');

const MAX_BATCH_SIZE = 100;
const FLUSH_INTERVAL_MS = 2000;

/** Queued items awaiting the next flush -- see enqueue() for the shape. */
let queue = [];
let flushTimer = null;

/**
 * AsyncEventBatcher: buffers a CHAT/GIFT/JOIN event for Postgres persistence
 * instead of writing it immediately. `enqueue()` itself is a synchronous
 * array push -- no DB call happens on this call, so it adds ~0 overhead to
 * the Fast-Path Socket broadcast it's called right after in
 * liveStream.service.js (which was already fire-and-forget before this, but
 * still did a DB round trip per event).
 *
 * @param {{sessionId: number, eventType: 'CHAT'|'GIFT'|'JOIN', user: object,
 *   occurredAt: Date|undefined, extra: object, envelope: object}} item
 */
function enqueue(item) {
  queue.push(item);
  if (queue.length >= MAX_BATCH_SIZE) {
    flush();
  }
}

/** Starts the periodic flush timer. Call once at server startup. */
function init() {
  if (!flushTimer) {
    flushTimer = setInterval(flush, FLUSH_INTERVAL_MS);
  }
}

/**
 * Drains the queue and bulk-writes it to Postgres in one transaction.
 * `queue.splice()` up front is synchronous, so a flush() triggered by
 * hitting MAX_BATCH_SIZE while the periodic timer's flush() is still
 * in-flight just sees an empty queue and no-ops -- no separate lock needed.
 * Exported so liveStream.service.js can await a final flush when a session
 * closes (FR-35/36: the session report must not miss whatever was still
 * buffered).
 */
async function flush() {
  if (queue.length === 0) {
    return;
  }
  const batch = queue.splice(0, queue.length);

  const client = await db.pool.connect();
  try {
    await client.query('BEGIN');

    // app_users: de-dupe by tiktokUserId first -- a single INSERT ... ON
    // CONFLICT DO UPDATE statement can't touch the same conflicting row
    // twice. Last occurrence in the batch wins, matching the old per-event
    // upsert()'s "refreshed on every appearance" behavior.
    const usersByTiktokId = new Map();
    for (const item of batch) {
      usersByTiktokId.set(item.user.userId, {
        tiktokUserId: item.user.userId,
        username: item.user.uniqueId,
        nickname: item.user.nickname,
      });
    }
    const appUserIdByTiktokId = await appUserRepository.bulkUpsert(client, [...usersByTiktokId.values()]);

    // events + payloads: grouped by type, because comment/gift/join_payloads
    // each need the events.id FK generated by inserting into `events` first.
    for (const eventType of ['CHAT', 'GIFT', 'JOIN']) {
      const items = batch.filter((item) => item.eventType === eventType);
      if (items.length === 0) {
        continue;
      }

      const eventIds = await eventRepository.bulkInsertEvents(
        client,
        items.map((item) => ({
          sessionId: item.sessionId,
          appUserId: appUserIdByTiktokId.get(item.user.userId),
          eventType,
          occurredAt: item.occurredAt,
        }))
      );

      if (eventType === 'CHAT') {
        await eventRepository.bulkInsertCommentPayloads(
          client,
          items.map((item, idx) => ({ eventId: eventIds[idx], comment: item.extra.comment }))
        );
      } else if (eventType === 'GIFT') {
        await eventRepository.bulkInsertGiftPayloads(
          client,
          items.map((item, idx) => ({ eventId: eventIds[idx], ...item.extra }))
        );
      } else {
        await eventRepository.bulkInsertJoinPayloads(
          client,
          items.map((item, idx) => ({ eventId: eventIds[idx], viewerCount: item.extra.viewerCount }))
        );
      }
    }

    // raw_live_events: independent of the normalized write above, same as
    // before (separate table, one failing must never block the other).
    await rawLiveEventRepository.bulkCreate(
      client,
      batch.map((item) => ({
        eventId: item.envelope.eventId,
        sessionId: item.sessionId,
        eventType: item.envelope.type,
        rawPayload: item.envelope,
      }))
    );

    await client.query('COMMIT');
    logger.debug(`Flushed batch of ${batch.length} event(s)`);
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    logger.error('Batch flush failed, events not persisted', { error: err.message, batchSize: batch.length });
  } finally {
    client.release();
  }
}

module.exports = { init, enqueue, flush };
